---
title: "Sample Report"
output: pdf_document
header-includes:
    - \usepackage{sectsty}
    - \allsectionsfont{\color{blue}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

## R Markdown

This is a finding I'd want to show.

```{R echo=FALSE}
library(ggplot2)
library(ggthemes)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```


# Stacked Bar Plot with Colors and Legend
```{r echo=FALSE}
counts <- table(mtcars$gear, mtcars$vs)
barplot(counts, main="Car Distribution by Gears and VS",
  xlab="Number of Gears", col=c("darkblue","red"),
  legend = rownames(counts))
```

  
# Stacked ggplot
```{R echo=FALSE}
nubc21 <- read.csv(file = 'nubc2021.csv')

qn100_1.tb <- table(nubc21$mx.QN100_1) 
qn100_1.df <- data.frame(qn100_1.tb, Ques = c(0))
levels(qn100_1.df$Var1) <- c("Strongly disagree","Disagree",
                             "Somewhat disagree","Somewhat agree",
                             "Agree","Strongly Agree","No opinion/Not applicable")

prop <- as.integer(100*qn100_1.df$Freq/sum(qn100_1.df$Freq))
for(i in 1:length(prop)){
  if(as.integer(prop[i])<5)
    prop[i] = ''
  else
    prop[i] = paste0(prop[i], "%")
}

p <- ggplot(data = qn100_1.df, aes(x=Ques, y=Freq, fill=Var1))+
  geom_bar(stat = "identity", width = 0.001)+
  geom_col()+geom_text(aes(label = prop),
                       position = position_stack(vjust = 0.5)) +
  theme_economist(base_size = 14) +
  scale_fill_economist() +
  theme(legend.position = "bottom", 
        legend.title = element_blank()) +
  ylab(NULL) +
  xlab(NULL) +
  xlim(-5,5) +
  theme(axis.line = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank()) +
  coord_cartesian(ylim = c(0,10000)) +
  coord_flip()
p
```
OKAY TEXT HERE \
```{R echo=FALSE}
p
```
Roses are $\color{red}{\text{beautiful red}}$, 
violets are $\color{blue}{\text{lovely blue}}$.
